### ISSUE TITLE
No JS SDK for the Candy machine v2?

### ISSUE THREAD

**Issue by duguorong009** [metaplex-foundation/metaplex-program-library#143] opened 2022-01-24 15:09 UTC
Is there any JS SDK generated for the Candy machine v2?
Currently, only cli tool is supported for the CMv2.
And, there is no JS SDK for CMv2, which the developers can use for the Dapp development.
Any block for this issue?
It would be cool to have the SDK generated.

**Comment by aheckmann** [comment] 2022-01-25 20:12
Duplicate of #46. Closing.

**Closed by aheckmann** 2022-01-25 20:12 UTC
