### ISSUE TITLE
[Bug]: punish_bots returns Ok() instead of error

### ISSUE THREAD

**Issue by 0xabstracted** [metaplex-foundation/metaplex-program-library#574] opened 2022-06-30 05:27 UTC
### Which package is this bug report for?

candy-machine

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

After punish_bots is called we are returning Ok(()), which will let the instruction pass and will make look like the whole mint transaction is successful and it leaves the associated token accounts and mint coounts open. As a result tokens without metadata are shown in wallets.

### Priority this issue should have

Low (slightly annoying)

**Comment by samuelvanderwaal** [comment] 2022-06-30 17:54
If you fail the transaction the bots don't actually get charged so the transaction has to pass.

**Comment by febo** [comment] 2022-10-20 09:49
Indeed, in oder to charge the *bot fee*, the transaction has to succeed. I will close this issue since this is the intended behaviour.

**Closed by febo** 2022-10-20 09:49 UTC
Labels: bug
