### ISSUE TITLE
[Bug]: Autogenerated SDKs have payer as non-mutable, leading to errors

### ISSUE THREAD

**Issue by SkullTech** [metaplex-foundation/metaplex-program-library#383] opened 2022-04-17 08:17 UTC
### Which package is this bug report for?

token-metadata

### Issue description

I'm using the following function to mint an NFT

```ts
export const mintNftV2 = async (
  provider: anchor.Provider,
  creator: anchor.web3.Keypair,
  destination: anchor.web3.PublicKey,
  collectionMint?: anchor.web3.PublicKey
) => {
  const mint = await createMint(
    provider.connection,
    creator,
    creator.publicKey,
    null,
    0
  );

  const tokenAccount = await createAssociatedTokenAccount(
    provider.connection,
    creator,
    mint,
    destination
  );

  await mintToChecked(
    provider.connection,
    creator,
    mint,
    tokenAccount,
    creator.publicKey,
    1,
    0
  );

  // Set Metadata
  const metadata = await getTokenMetadata(mint);
  const transaction = new anchor.web3.Transaction();

  transaction.add(
    createCreateMetadataAccountV2Instruction(
      {
        metadata,
        mint,
        mintAuthority: creator.publicKey,
        updateAuthority: creator.publicKey,
        payer: creator.publicKey,
      },
      {
        createMetadataAccountArgsV2: {
          isMutable: false,
          data: {
            name: "Pretty Cool NFT",
            symbol: "PCN",
            sellerFeeBasisPoints: 10,
            uri: "https://pretty-cool-nft.xyz/metadata",
            creators: [
              {
                address: creator.publicKey,
                share: 100,
                verified: false,
              },
            ],
            collection: collectionMint
              ? { key: collectionMint, verified: false }
              : null,
            uses: null,
          },
        },
      }
    )
  );

  const txSign = await provider.send(transaction, [creator]);
  await provider.connection.confirmTransaction(txSign);

  // Set mint authority to null
  await setAuthority(
    provider.connection,
    creator,
    mint,
    creator,
    AuthorityType.MintTokens,
    null
  );

  return mint;
};
```

But I'm getting the following error

```
     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Cross-program invocation with unauthorized signer or writable account
```

Looking through the program logs, these are the logs I find

```
'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]',
    'Program log: Instruction: Create Metadata Accounts v2',
    'Program log: Transfer 5616720 lamports to the new account',
    "FHjNBQU13gkJDDnuY2Z8vtwnzYuZTPVsnRVvhmqatL7's writable privilege escalated",
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 12049 of 1400000 compute units',
    'Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Cross-program invocation with unauthorized signer or writable account'
```

Digging through the source code, I found that [this line](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/token-metadata/js/src/generated/instructions/CreateMetadataAccountV2.ts#L99 ) has the `payer` set as read-only, whereas it should be `writable`. Making the change locally and then running the above code again works, no errors.

As the TS SDK is autogenerated by Solita, there must be something going wrong either with the Rust source code or Solita. Please look into it and fix it on a priority basis, because without this none of the functions are useable. Not just `createCreateMetadataAccountV2Instruction`, I checked that all of the autogenerated functions has this bug.

### Relevant log output

```shell
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Cross-program invocation with unauthorized signer or writable account
     Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
     Program log: Instruction: Create Metadata Accounts v2
     Program log: Transfer 5616720 lamports to the new account
     FHjNBQU13gkJDDnuY2Z8vtwnzYuZTPVsnRVvhmqatL7's writable privilege escalated
     Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 12049 of 1400000 compute units
     Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: Cross-program invocation with unauthorized signer or writable account
```

### Priority this issue should have

High (immediate attention needed)

**Comment by SkullTech** [comment] 2022-04-25 06:51
Any update on this? @thlorenz

**Comment by thlorenz** [comment] 2022-04-25 13:38
Solita correctly generates payer as non-writable since it is [marked as such](https://github.com/metaplex-foundation/metaplex-program-library/blob/thlorenz/chore/simpler-solita/token-metadata/program/src/instruction.rs#L274).

We are using this instruction [successfully in the new SDK](https://github.com/metaplex-foundation/js-next/blob/thlorenz/feat/candy-machine-create/src/programs/tokenMetadata/transactionBuilders/createMetadataV2Builder.ts), therefore I'm certain this configuration is correct.

Did you actually try to manually edit the code to make payer _writable_ and did it fix your problem.
I'm thinking that your issue is caused by something else.

cc @lorisleiva

**Comment by lorisleiva** [comment] 2022-04-25 14:26
I'm slightly confused as to why this would work using the new SDK but not using the autogenerated instruction directly.

That being said, looking at [the instruction factory on the program](https://github.com/metaplex-foundation/metaplex-program-library/blob/5d13c31fec61651937033d26c295b9851da4b62d/token-metadata/program/src/instruction.rs#L474), it does look like the `payer` should be `writable`.

However, the comments say it should be `signer` inferring it does not need to be writable which is super confusing. That was also the case in the comments that got replaced by the Shank macros which is why they inherited that configuration.

Before we make the `payer` writable, I'd just like to make sure it's the right thing to do because again it does work with the SDK.

**Comment by SkullTech** [comment] 2022-04-25 14:40
Yeah that's confusing to me as well. One possibility is that, if the `payer` is same as the `provider.wallet` then it gets overwritten cause the provider.wallet is always marked as `writable`, and maybe that's why the js-next SDK code is working.

**Comment by SkullTech** [comment] 2022-04-25 14:46
Cfqd in the Anchor discord pointed out this bug, and he said this

<img width="869" alt="Screenshot 2022-04-25 at 8 14 56 PM" src="https://user-images.githubusercontent.com/16862545/165113388-76a69e8e-7192-4a58-929d-eb64d6b257e7.png">

**Closed** 2022-04-26 14:59 UTC
Labels: bug
