### ISSUE TITLE
Deploy on localhost error: Code not parseable: Error("space must be provided with init")

### ISSUE THREAD

**Issue by hungphannapaglobal** [metaplex-foundation/metaplex-program-library#528] opened 2022-06-09 03:40 UTC
### Which package is this bug report for?

candy-machine

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

Devnet is died, Candy machine program is old. So i can't test my project on these network. I decides to deploy on localhost to for easy and fast to test. Everything fine with build. But I get error when deploy program.   
Following steps describe when i get error

1. `cd ./candy-machine/program ` : fine
2. `anchor build --idl ./target/idl`    : fine
3. `anchor deploy --provider.cluster localnet` : error

can you help me fix this error or tell me the way to deploy candy machine on localhost

### Relevant log output

```shell
BPF SDK: /home/hungphan/.local/share/solana/install/releases/stable-9a07547352645fb20e038e139f8536710b1f36e6/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.16s
cargo-build-bpf child: /home/hungphan/.local/share/solana/install/releases/stable-9a07547352645fb20e038e139f8536710b1f36e6/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/hungphan/Documents/test/metaplex-program-library/candy-machine/program/target/deploy/mpl_candy_machine.so

To deploy this program:
  $ solana program deploy /home/hungphan/Documents/test/metaplex-program-library/candy-machine/program/target/deploy/mpl_candy_machine.so
The program address will default to this keypair (override with --program-id):
  /home/hungphan/Documents/test/metaplex-program-library/candy-machine/program/target/deploy/mpl_candy_machine-keypair.json
Deploying workspace: http://localhost:8899
Upgrade authority: /home/hungphan/.config/solana/id.json
thread 'main' panicked at 'Code not parseable: Error("space must be provided with init")', lang/syn/src/idl/file.rs:360:58
stack backtrace:
   0:     0x55b8f0e5b0ca - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b8f0e5b0ca - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b8f0e5b0ca - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b8f0e5b0ca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b8f0b739cc - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x55b8f0e59984 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x55b8f0e5a240 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b8f0e5a240 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b8f0e5a240 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x55b8f0e595d2 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x55b8f0e595d2 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x55b8f0e8bd48 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:     0x55b8f0e8bcc6 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55b8f0e8bc82 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x55b8f08b0ce0 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x55b8f08b0fc2 - core::result::unwrap_failed::hb53671404b9e33c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
  16:     0x55b8f0aeecc6 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h182dc9f3766a2ec6
  17:     0x55b8f0acc041 - anchor_syn::idl::file::parse_account_derives::h4f0a6799c86cea8b
  18:     0x55b8f0948a60 - anchor_syn::idl::file::parse::h1e3eca0ac74f0080
  19:     0x55b8f09482a7 - anchor_cli::config::WithPath<anchor_cli::config::Config>::read_all_programs::h0063ecc42f9b67d7
  20:     0x55b8f09e6adf - anchor_cli::deploy::h320e13a4747e2c5e
  21:     0x55b8f09c8d7a - anchor_cli::entry::h25ae5351f6f701af
  22:     0x55b8f08c538f - anchor::main::h48ee933ebaa75750
  23:     0x55b8f08c3d53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7372e78ae355b653
  24:     0x55b8f08c5d87 - main
  25:     0x7f06baa27083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  26:     0x55b8f08c3c6a - _start
  27:                0x0 - <unknown>
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by paspalabab** [comment] 2022-06-10 13:35
same problem with anchor build, hope it to be fixed soon. i was also trying to deploy on localhost and encountered this error

**Comment by stranzhay** [comment] 2022-06-17 22:59
hi @hungphannapaglobal are you still getting this error ? so far I am unable to reproduce with the steps provided.

**Comment by stranzhay** [comment] 2022-06-22 23:38
closing for now. unable to reproduce with both solana deploy and anchor deploy. if this is still an issue, please reopen.

**Closed by stranzhay** 2022-06-22 23:38 UTC
Labels: bug
